name: Release Version
on:
  release:
    type: released
jobs:
  check-release-version:
    runs-on: ubuntu-latest
    output:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2
        run: echo ${{ version=steps.get_version.outputs.version }} >> $GITHUB_OUTPUT